### ISSUE TITLE
Error while running the samples index locally

### ISSUE THREAD

**Issue by Miroku87** [anthonymoralez/jsiso-samples#2]
Hi!
I have installed this package with node and now I'm running it with npm.
Then I navigate to localhost:1337 with Chrome 35 and I see a blue page like the ones on the website.
But then nothing happens.
Looking at the JS Console in Chrome I see this error:

```
Uncaught TypeError: Cannot read property 'length' of undefined - Field.js:89
```

**Comment by beakable** [comment]
Hey guys, I'll sort this out today. I didn't receive notifications for the post by Miroku87. I'll continue this thread here: https://github.com/beakable/isometric/issues/9.

Thanks,

Iain
